### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by fungos** [mgerhardy/fips-googletest#2]
I don't know if you're still using this project somewhere, but It would be nice to rename the macros to something more simple like `gtest_begin` and `gtest_end`. What do you think?

For the main code generation, it may be optional or we can find a better way to generate and use it. You had a FIXME, so maybe we can work on something nice and fix this.

Also the begin macro uses the current application defined? This means that we must declare de test after or within each fips_begin/end block? Adding this little more info on the readme may be useful and almost let it complete.

I'm planning on using gtests more frequently, so it may be really cool to have it getting in shape.

**Comment by mgerhardy** [comment]
Will give it a try 

## 

Martin Gerhardy
http://www.caveproductions.org

**Comment by mgerhardy** [comment]
renamed the macros and added more details to the readme to show a full example

**Comment by mgerhardy** [comment]
about the code generation - I would really like to have a configure_file here that would use the template from the project dir - or if no is provided here, the one that comes with fips-googletest

**Comment by mgerhardy** [comment]
e99587221d85a52c7c591d9ec62f02ec78e88784

**Comment by fungos** [comment]
Yes, good idea. You can make something like [this](https://github.com/floooh/fips/blob/master/cmake/fips.cmake#L546-L559).

For example, to be able to use this way: `gtest_begin(MyTests TEMPLATE path/to/mytemplate.cpp.in)` and even when not wanting to use a template: `gtest_begin(MyTests2 WITHOUT_TEMPLATE)` to use cases as in assimp needs ([see this if](https://github.com/fungos/fips-googletest/blob/fips-assimp/fips-include.cmake#L38))

**Comment by fungos** [comment]
I've implemented my suggestions on this PR. I've merged your fixes there so it should be good to merge back to your master.
